"""
Registry of all supported AI providers.
"""

PROVIDERS = {
    "openai": {
        "name": "OpenAI",
        "base_url": "https://api.openai.com/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai",
        "hardcoded_models": None,
    },
    "anthropic": {
        "name": "Anthropic",
        "base_url": "https://api.anthropic.com",
        "models_endpoint": None,
        "auth_type": "x-api-key",
        "sdk": "anthropic",
        "hardcoded_models": [
            "claude-opus-4-7",
            "claude-sonnet-4-6",
            "claude-haiku-4-5-20251001",
            "claude-3-5-sonnet-20241022",
            "claude-3-5-haiku-20241022",
            "claude-3-opus-20240229",
        ],
    },
    "google": {
        "name": "Google Gemini",
        "base_url": "https://generativelanguage.googleapis.com/v1beta",
        "models_endpoint": "/models",
        "auth_type": "query_key",
        "sdk": "google",
        "hardcoded_models": None,
    },
    "mistral": {
        "name": "Mistral AI",
        "base_url": "https://api.mistral.ai/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
    "cohere": {
        "name": "Cohere",
        "base_url": "https://api.cohere.ai/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "cohere",
        "hardcoded_models": None,
    },
    "groq": {
        "name": "Groq",
        "base_url": "https://api.groq.com/openai/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
    "together": {
        "name": "Together AI",
        "base_url": "https://api.together.ai/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
    "perplexity": {
        "name": "Perplexity AI",
        "base_url": "https://api.perplexity.ai",
        "models_endpoint": None,
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": [
            "llama-3.1-sonar-small-128k-online",
            "llama-3.1-sonar-large-128k-online",
            "llama-3.1-sonar-huge-128k-online",
        ],
    },
    "deepseek": {
        "name": "DeepSeek",
        "base_url": "https://api.deepseek.com/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
    "xai": {
        "name": "xAI (Grok)",
        "base_url": "https://api.x.ai/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
    "openrouter": {
        "name": "OpenRouter",
        "base_url": "https://openrouter.ai/api/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
    "huggingface": {
        "name": "Hugging Face",
        "base_url": "https://api-inference.huggingface.co/v1",
        "models_endpoint": None,
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": [
            "meta-llama/Llama-3.1-8B-Instruct",
            "meta-llama/Llama-3.1-70B-Instruct",
            "mistralai/Mistral-7B-Instruct-v0.3",
        ],
    },
    "replicate": {
        "name": "Replicate",
        "base_url": "https://api.replicate.com/v1",
        "models_endpoint": None,
        "auth_type": "bearer",
        "sdk": "replicate",
        "hardcoded_models": None,
    },
    "fireworks": {
        "name": "Fireworks AI",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
    "anyscale": {
        "name": "Anyscale",
        "base_url": "https://api.endpoints.anyscale.com/v1",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
    "ollama": {
        "name": "Ollama (local)",
        "base_url": "http://localhost:11434",
        "models_endpoint": "/api/tags",
        "auth_type": "none",
        "sdk": "ollama",
        "hardcoded_models": None,
    },
    "lmstudio": {
        "name": "LM Studio (local)",
        "base_url": "http://localhost:1234",
        "models_endpoint": "/v1/models",
        "auth_type": "none",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
    "azure": {
        "name": "Azure OpenAI",
        "base_url": "",  # user fills in
        "models_endpoint": "/openai/deployments",
        "auth_type": "api-key",
        "sdk": "azure_openai",
        "hardcoded_models": None,
    },
    "custom": {
        "name": "Personalizado",
        "base_url": "",
        "models_endpoint": "/models",
        "auth_type": "bearer",
        "sdk": "openai_compat",
        "hardcoded_models": None,
    },
}


def get_provider(provider_id: str) -> dict:
    return PROVIDERS.get(provider_id, PROVIDERS["custom"])
